apiVersion: v1
kind: Service
metadata:
  name: mysite
  annotations:
    external-dns.alpha.kubernetes.io/hostname: www.boom-tube.net.
spec:
  type: LoadBalancer
  selector:
    app: mysite
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000