apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite-deplayment
  labels:
    app: mysite
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysite
  template:
    metadata:
      labels:
        app: mysite
    spec:
      volumes:
      - name: mysitedb
        persistentVolumeClaim:
          claimName: data-postgres-0
      containers:
      - name: mysite
        image: ghcr.io/victornav9/cis-92:main
        imagePullPolicy: Always
        volumeMounts:
        - name: mysitedb
          mountPath: /var/lib/postgresql/data
          subPath: mysitedb
        livenessProbe:
          httpGet:
            path: /polls/
            port: 8000
          initialDelaySeconds: 10
        resources:
          limits:
            cpu: 250m 
            memory: 512Mi
            ephemeral-storage: 10Mi
        ports:
        - containerPort: 8000
        env:
        - name: DB_ENGINE
          value: "postgres"
        - name: DB_NAME
          value: "mysitedb"
        - name: DB_USER
          value: "mysiteuser"
        - name: DB_HOST
          value: "postgres"
        - name: DB_PASSWORD
          value: "mysitepassword"
        - name: DJANGO_ADMIN_EMAIL
          value: "test@test.test"
        - name: DJANGO_ADMIN_USERNAME
          value: "test"
        - name: DJANGO_SUPERUSER_PASSWORD
          value: "testtest"