apiVersion: v1
kind: Pod
metadata:
  name: mysite
  labels:
    app: mysite
spec:
  volumes:
  - name: mysitedb
    persistentVolumeClaim:
      claimName: postgrespvc
  containers:
  - name: mysite
    image: ghcr.io/victornav9/cis-92:main
    imagePullPolicy: Always
    volumeMounts:
    - name: mysitedb
      mountPath: /var/lib/postgresql/data
      subPath: mysitedb
    livenessProbe:
      httpGet:
        path: /polls/
        port: 8000
    resources:
      limits:
        cpu: 250m 
        memory: 512Mi
        ephemeral-storage: 10Mi
    ports:
    - containerPort: 8000
    env:
    - name: DB_ENGINE
      value: "postgres"
    - name: DB_NAME
      value: "django"
    - name: DB_USER
      value: "django"
    - name: DB_HOST
      value: "172.19.176.3"
    - name: DB_PASSWORD
      value: "django"
    - name: DJANGO_ADMIN_EMAIL
      value: "test@test.test"
    - name: DJANGO_ADMIN_USERNAME
      value: "test"
    - name: DJANGO_SUPERUSER_PASSWORD
      value: "testtest"