apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  volumes:
  - name: postgresdb
    persistentVolumeClaim:
      claimName: postgrespvc
  containers:
  - name: postgres
    image: docker.io/postgres:14.2
    imagePullPolicy: Always
    volumeMounts:
    - name: postgresdb
      mountPath: /var/lib/postgresql/data
      subPath: postgresdb
    resources:
      limits:
        cpu: 250m 
        memory: 512Mi
        ephemeral-storage: 10Mi
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_DB
      value: "mysitedb"
    - name: POSTGRES_USER
      value: "mysiteuser"
    - name: POSTGRES_PASSWORD
      value: "mysitepassword"